### PR TITLE
Add Blade SVG to composer.json

### PR DESCRIPTION
**Pull request by xewl**
Seems like it's missing.

### CODE REVIEW

**Comment by xewl** [comment]
Reason:

`composer update`

```
...
@php artisan package:discover

In ProviderRepository.php line 208:

  Class 'BladeSvg\BladeSvgServiceProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
vagrant@lanarea:~/code$ composer require BladeSvg/BladeSvgServiceProvider


  [InvalidArgumentException]
  Could not find a matching version of package BladeSvg/BladeSvgServiceProvid
  er. Check the package spelling, your version constraint and that the packag
  e is available in a stability which matches your minimum-stability (stable)
  .
```

**Comment by xewl** [comment]
I know what you mean, it was the busiest period I've ever had, guess it's the season (:

I was just reviewing, or at least trying to... some issues rose up with every step I tried xD
Nothing I couldn't solve though B)

I'll definitely look into this project some more!

**Comment by bpocallaghan** [comment]
Hi @xewl 
Yeah - think everything realized its the end of 2017 :)

Awesome, please shout if anything pops up. I personally use wamp + windows, might be able to help with some windows related issues.

Also now with Chrome forcing https for .dev, you will need to change it to .test or .d3v or something else (will give it sometime to see what most of the community are going with)

Have fun, thanks for giving this a shot.

**Comment by xewl** [comment]
Both taken account for ;) I changed to .vagrant (and you can skip with typing "badidea" too ;)
Wamp's installed just for PHP 7.1's purpose, but I mostly use homestead for Laravel tho'

**Pull request merged**
